name: Build and Repair Voice Assistant

on:
  push:
    branches:
      - main

jobs:
  repair-project:
    if: contains(github.event.head_commit.message, '[repair]')
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permission to commit back to the repo
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Remove old android directory
        run: rm -rf ./android

      - name: Regenerate Android project files
        run: flutter create --platforms=android --project-name=rafiq_app .

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(auto): Regenerate Android project structure"
          branch: main

  build:
    # Run on every push that IS NOT a repair commit
    if: "!contains(github.event.head_commit.message, '[repair]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build release APK
        run: flutter build apk --release

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: rafiq-app-release
          path: build/app/outputs/flutter-apk/app-release.apk