name: Build Flutter App

on:
  push:
    branches:
      - main # Or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Create local.properties
        run: echo "flutter.sdk=$FLUTTER_ROOT" > android/local.properties

      - name: Build Android APK
        run: flutter build apk --release

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: rafiq-app-release
          path: build/app/outputs/flutter-apk/app-release.apk